### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by moondev** [tmcinerney/keep#6]
Hi there. I love the app! Exactly what I was looking for.

I wanted your thoughts on a feature I was thinking about. The ability to show a number of "to-do" tasks in the menu bar that is linked to a checklist (perhaps first pinned)

I can also help with development, but wasn't sure if google keep had an api to even make this possible.

**Comment by tmcinerney** [comment]
Thanks, I'm surprised someone is using it :)

I don't think there is a Google Keep API yet. We could also use labels as a way to pull out notes that have checklists in them I guess. But I think we would have to wait for an API to exist though.
