### ISSUE TITLE
Homebrew Cask Integration 🖥️

### ISSUE THREAD

**Issue by FrancesCoronel** [tmcinerney/keep#7]
I would love for this app to be added to [Homebrew Cask](https://github.com/caskroom/homebrew-cask) so it can be installed more easily. 

---

> Some context...

 Homebrew-Cask extends Homebrew and brings its elegance, simplicity, and speed to the installation and management of GUI macOS applications such as Atom and Google Chrome.

We do this by providing a friendly Homebrew-style CLI workflow for the administration of macOS applications distributed as binaries.

**Comment by FrancesCoronel** [comment]
Hope it's cool but yeah I created a PR https://github.com/caskroom/homebrew-cask/pull/40393 because I had some free time. 🍺

**Comment by tmcinerney** [comment]
Hah, thanks for that! I updated some dependencies and shipped `v1.0.0` and have a PR to update the cask: https://github.com/caskroom/homebrew-cask/pull/40979
