### ISSUE TITLE
Reduce CPU usage

### ISSUE THREAD

**Issue by brechtm** [tmcinerney/keep#9]
Thank you for a very useful app!

I noticed that Keep is often causing significant CPU load, even when I'm not interacting with it. For example, Keep is now constantly using around 3% and Keep Helper 6% of the CPU. This reduces battery life of my MacBook significantly, so I can't afford to have Keep running all the time.

**Comment by brechtm** [comment]
I had a go at implementing Keep as a native macOS application. [GoogleKeepMenu](https://github.com/brechtm/GoogleKeepMenu) is the result. I hope you don't mind I copied your status bar icon?

**Comment by tmcinerney** [comment]
I think this would likely be due to Electron, which often has complaints around high CPU/memory utilization. Nice work on the macOS version, and no worries about using the icon :)
